export const GET_PRODUCT_REQUEST = '@GET_PRODUCT_REQUEST';
export const PRODUCT_REQUEST_SUCCESS = '@PRODUCT_REQUEST_SUCCESSS';
export const PRODUCT_REQUEST_FAILURE = '@PRODUCT_REQUEST_FAILURE';

export const REMOVE_PRODUCT_REQUEST = '@REMOVE_PRODUCT_REQUEST';
export const REMOVE_PRODUCT_SUCCESS = '@REMOVE_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT_FAILURE = '@REMOVE_PRODUCT_FAILURE';
